# =========================
# Language configuration
# =========================

LANG_NAMES = {
    "th": "Thai",
    "ja": "Japanese",
    "en": "English",
    "zh": "Chinese",
    "ko": "Korean",
    "ru": "Russian",
    "vi": "Vietnamese",
    "fil": "Filipino",
    "fil-PH": "Filipino (PH)",
    "tl": "Tagalog",
    "id": "Indonesian",
    "hi": "Hindi",
    "km": "Khmer",
    "my": "Burmese",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "it": "Italian",
    "pt": "Portuguese",
    "pl": "Polish",
    "uk": "Ukrainian",
    "ar": "Arabic",
}

FLAGS = {
    "th": "🇹🇭",
    "en": "🇺🇸",
    "ja": "🇯🇵",
    "zh": "🇨🇳",     
    "ko": "🇰🇷",
    "ru": "🇷🇺",
    "vi": "🇻🇳",
    "fil": "🇵🇭",
    "fil-PH": "🇵🇭",
    "tl": "🇵🇭",
    "id": "🇮🇩",
    "hi": "🇮🇳",
    "km": "🇰🇭",    
    "my": "🇲🇲",     
    "fr": "🇫🇷",
    "de": "🇩🇪",
    "es": "🇪🇸",
    "it": "🇮🇹",
    "pt": "🇵🇹",
    "pl": "🇵🇱",
    "uk": "🇺🇦",
    "ar": "🇸🇦",     
}
